#
# Support PHP versions: http://windows.php.net/downloads/releases/
#
build: false
clone_depth: 1
clone_folder: C:\projects\php-coveralls

platform:
  # x86
  - x64

environment:
  matrix:
    # php_ver: 5.5.38
    - php_ver: 5.6.30
    # php_ver: 7.0.16
    - php_ver: 7.1.3

cache:
  - '%APPDATA%\Composer'
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
  - C:\projects\php-coveralls\vendor
  - C:\Tools\composer.phar
  - C:\Tools\php -> appveyor.yml

install:
  #MEMO: This setting is temporary at 2017-03-12
  - ps: Set-Service wuauserv -StartupType Manual

  - choco install php --params '/InstallDir:C:\Tools\php' --version %php_ver%
  - SET PATH=C:\Tools\php;%PATH%
  - cd C:\Tools\php
  - sed -i 's:^;date.timezone =:date.timezone="America/Los_Angeles":' php.ini
  - sed -i 's/^;extension=php_openssl/extension=php_openssl/' php.ini
  - sed -i 's/^;extension=php_mbstring/extension=php_mbstring/' php.ini

  - cd C:\Tools
  - php -r "readfile('https://getcomposer.org/installer');" | php

  - php C:\Tools\composer.phar global require "phpunit/phpunit"
  - SET PATH=%APPDATA%\Composer\vendor\bin;%PATH%

  - cd C:\projects\php-coveralls
  - mkdir build\logs
  - php C:\Tools\composer.phar update --prefer-stable --no-interaction

test_script:
  - cd C:\projects\php-coveralls
  - phpunit
  #TODO: xdebug will install
  # bin\coveralls -v --exclude-no-stmt
