name: Build PHAR

on:
    - pull_request
    - push

jobs:
    phar:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.0
                    coverage: none

            -   name: Build PHAR
                run: |
                    curl -LSs https://box-project.github.io/box2/installer.php | php
                    composer config platform.php 2> /dev/null || composer config platform.php 5.5.0
                    composer update --no-dev --no-interaction --optimize-autoloader --no-interaction --no-progress
                    php -d phar.readonly=false box.phar build
